sudo ./../energy/AppPowerMeter ./nbench 0 >> results/power0.txt
sudo ./../energy/AppPowerMeter ./nbench 1 >> results/power1.txt
sudo ./../energy/AppPowerMeter ./nbench 2 >> results/power2.txt
sudo ./../energy/AppPowerMeter ./nbench 3 >> results/power3.txt
sudo ./../energy/AppPowerMeter ./nbench 4 >> results/power4.txt
sudo ./../energy/AppPowerMeter ./nbench 5 >> results/power5.txt
sudo ./../energy/AppPowerMeter ./nbench 6 >> results/power6.txt
sudo ./../energy/AppPowerMeter ./nbench 7 >> results/power7.txt
sudo ./../energy/AppPowerMeter ./nbench 8 >> results/power8.txt
sudo ./../energy/AppPowerMeter ./nbench 9 >> results/power9.txt
sudo ./../energy/AppPowerMeter ./nbench 0 >> results/power0.txt
sudo ./../energy/AppPowerMeter ./nbench 1 >> results/power1.txt
sudo ./../energy/AppPowerMeter ./nbench 2 >> results/power2.txt
sudo ./../energy/AppPowerMeter ./nbench 3 >> results/power3.txt
sudo ./../energy/AppPowerMeter ./nbench 4 >> results/power4.txt
sudo ./../energy/AppPowerMeter ./nbench 5 >> results/power5.txt
sudo ./../energy/AppPowerMeter ./nbench 6 >> results/power6.txt
sudo ./../energy/AppPowerMeter ./nbench 7 >> results/power7.txt
sudo ./../energy/AppPowerMeter ./nbench 8 >> results/power8.txt
sudo ./../energy/AppPowerMeter ./nbench 9 >> results/power9.txt
sudo ./../energy/AppPowerMeter ./nbench 0 >> results/power0.txt
sudo ./../energy/AppPowerMeter ./nbench 1 >> results/power1.txt
sudo ./../energy/AppPowerMeter ./nbench 2 >> results/power2.txt
sudo ./../energy/AppPowerMeter ./nbench 3 >> results/power3.txt
sudo ./../energy/AppPowerMeter ./nbench 4 >> results/power4.txt
sudo ./../energy/AppPowerMeter ./nbench 5 >> results/power5.txt
sudo ./../energy/AppPowerMeter ./nbench 6 >> results/power6.txt
sudo ./../energy/AppPowerMeter ./nbench 7 >> results/power7.txt
sudo ./../energy/AppPowerMeter ./nbench 8 >> results/power8.txt
sudo ./../energy/AppPowerMeter ./nbench 9 >> results/power9.txt
sudo ./../energy/AppPowerMeter ./nbench 0 >> results/power0.txt
sudo ./../energy/AppPowerMeter ./nbench 1 >> results/power1.txt
sudo ./../energy/AppPowerMeter ./nbench 2 >> results/power2.txt
sudo ./../energy/AppPowerMeter ./nbench 3 >> results/power3.txt
sudo ./../energy/AppPowerMeter ./nbench 4 >> results/power4.txt
sudo ./../energy/AppPowerMeter ./nbench 5 >> results/power5.txt
sudo ./../energy/AppPowerMeter ./nbench 6 >> results/power6.txt
sudo ./../energy/AppPowerMeter ./nbench 7 >> results/power7.txt
sudo ./../energy/AppPowerMeter ./nbench 8 >> results/power8.txt
sudo ./../energy/AppPowerMeter ./nbench 9 >> results/power9.txt
sudo ./../energy/AppPowerMeter ./nbench 0 >> results/power0.txt
sudo ./../energy/AppPowerMeter ./nbench 1 >> results/power1.txt
sudo ./../energy/AppPowerMeter ./nbench 2 >> results/power2.txt
sudo ./../energy/AppPowerMeter ./nbench 3 >> results/power3.txt
sudo ./../energy/AppPowerMeter ./nbench 4 >> results/power4.txt
sudo ./../energy/AppPowerMeter ./nbench 5 >> results/power5.txt
sudo ./../energy/AppPowerMeter ./nbench 6 >> results/power6.txt
sudo ./../energy/AppPowerMeter ./nbench 7 >> results/power7.txt
sudo ./../energy/AppPowerMeter ./nbench 8 >> results/power8.txt
sudo ./../energy/AppPowerMeter ./nbench 9 >> results/power9.txt