{ time ./nbench 0 2> sleep.stderr ; } 2>> results/bench0.txt
{ time ./nbench 1 2> sleep.stderr ; } 2>> results/bench1.txt
{ time ./nbench 2 2> sleep.stderr ; } 2>> results/bench2.txt
{ time ./nbench 3 2> sleep.stderr ; } 2>> results/bench3.txt
{ time ./nbench 4 2> sleep.stderr ; } 2>> results/bench4.txt
{ time ./nbench 5 2> sleep.stderr ; } 2>> results/bench5.txt
{ time ./nbench 6 2> sleep.stderr ; } 2>> results/bench6.txt
{ time ./nbench 7 2> sleep.stderr ; } 2>> results/bench7.txt
{ time ./nbench 8 2> sleep.stderr ; } 2>> results/bench8.txt
{ time ./nbench 9 2> sleep.stderr ; } 2>> results/bench9.txt
{ time ./nbench 0 2> sleep.stderr ; } 2>> results/bench0.txt
{ time ./nbench 1 2> sleep.stderr ; } 2>> results/bench1.txt
{ time ./nbench 2 2> sleep.stderr ; } 2>> results/bench2.txt
{ time ./nbench 3 2> sleep.stderr ; } 2>> results/bench3.txt
{ time ./nbench 4 2> sleep.stderr ; } 2>> results/bench4.txt
{ time ./nbench 5 2> sleep.stderr ; } 2>> results/bench5.txt
{ time ./nbench 6 2> sleep.stderr ; } 2>> results/bench6.txt
{ time ./nbench 7 2> sleep.stderr ; } 2>> results/bench7.txt
{ time ./nbench 8 2> sleep.stderr ; } 2>> results/bench8.txt
{ time ./nbench 9 2> sleep.stderr ; } 2>> results/bench9.txt
{ time ./nbench 0 2> sleep.stderr ; } 2>> results/bench0.txt
{ time ./nbench 1 2> sleep.stderr ; } 2>> results/bench1.txt
{ time ./nbench 2 2> sleep.stderr ; } 2>> results/bench2.txt
{ time ./nbench 3 2> sleep.stderr ; } 2>> results/bench3.txt
{ time ./nbench 4 2> sleep.stderr ; } 2>> results/bench4.txt
{ time ./nbench 5 2> sleep.stderr ; } 2>> results/bench5.txt
{ time ./nbench 6 2> sleep.stderr ; } 2>> results/bench6.txt
{ time ./nbench 7 2> sleep.stderr ; } 2>> results/bench7.txt
{ time ./nbench 8 2> sleep.stderr ; } 2>> results/bench8.txt
{ time ./nbench 9 2> sleep.stderr ; } 2>> results/bench9.txt
{ time ./nbench 0 2> sleep.stderr ; } 2>> results/bench0.txt
{ time ./nbench 1 2> sleep.stderr ; } 2>> results/bench1.txt
{ time ./nbench 2 2> sleep.stderr ; } 2>> results/bench2.txt
{ time ./nbench 3 2> sleep.stderr ; } 2>> results/bench3.txt
{ time ./nbench 4 2> sleep.stderr ; } 2>> results/bench4.txt
{ time ./nbench 5 2> sleep.stderr ; } 2>> results/bench5.txt
{ time ./nbench 6 2> sleep.stderr ; } 2>> results/bench6.txt
{ time ./nbench 7 2> sleep.stderr ; } 2>> results/bench7.txt
{ time ./nbench 8 2> sleep.stderr ; } 2>> results/bench8.txt
{ time ./nbench 9 2> sleep.stderr ; } 2>> results/bench9.txt
{ time ./nbench 0 2> sleep.stderr ; } 2>> results/bench0.txt
{ time ./nbench 1 2> sleep.stderr ; } 2>> results/bench1.txt
{ time ./nbench 2 2> sleep.stderr ; } 2>> results/bench2.txt
{ time ./nbench 3 2> sleep.stderr ; } 2>> results/bench3.txt
{ time ./nbench 4 2> sleep.stderr ; } 2>> results/bench4.txt
{ time ./nbench 5 2> sleep.stderr ; } 2>> results/bench5.txt
{ time ./nbench 6 2> sleep.stderr ; } 2>> results/bench6.txt
{ time ./nbench 7 2> sleep.stderr ; } 2>> results/bench7.txt
{ time ./nbench 8 2> sleep.stderr ; } 2>> results/bench8.txt
{ time ./nbench 9 2> sleep.stderr ; } 2>> results/bench9.txt