sprintf(buffer,"**System used for compilation:\n");
output_string(buffer);
sprintf(buffer,"**Linux elvenado 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 \n");
output_string(buffer);
sprintf(buffer,"**C compiler: gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) \n");
output_string(buffer);
sprintf(buffer,"**libc: libc-2.27.so\n");
output_string(buffer);
sprintf(buffer,"**Date of compilation: Tue  1 Sep 12:10:56 BST 2020\n");
output_string(buffer);
