sprintf(buffer,"**System used for compilation:\n");
output_string(buffer);
sprintf(buffer,"**Linux elvenado 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x\n");
output_string(buffer);
sprintf(buffer,"**C compiler: gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) \n");
output_string(buffer);
sprintf(buffer,"**libc: libc-2.27.so\n");
output_string(buffer);
sprintf(buffer,"**Date of compilation: Thu  6 Aug 16:41:17 BST 2020\n");
output_string(buffer);
